### ISSUE TITLE
rheobase algorithm does not catch Adaptive Exp spikes 

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/neuronunit#12]
@rgerkin 
Rheobase algorithm does not catch Adaptive Exp spikes which are typically non zero crossing. Although Adaptive Exp neurons clearly spike.

Proposed solutions:

* Offset all adexp voltages by a fixed amount. For spike extraction only. 

Drawbacks: will not generalize to other models that have non-zero crossing spikes.

Knock on effects: This might be the simplest, but it will probably distort other waveform measurements.

* Use a derivative approach to spike detection. 

Drawbacks: senses voltage deflections that are not genuine spikes, but just minor (non regenerative) voltage deflections caused by current injection.

* Systematically lower the threshold for threshold detection, if no supra injection values are found.

Knock-on effects: 
Complexity, capabilities spike_functions needs to sense differences in thresholod, and spike_detection methods used, so subsequent spike measurements used in spike_capabilities are consistant with spike sensing utilized in find_rheobase.

**Comment by rgerkin** [comment]
@russelljjarvis What does the membrane potential trace look like?  What do the equations look like?  Do they check for a threshold crossing (of a spike threshold, not a spike detection threshold), and then just set the membrane potential to the reset value?  If so, this will have lots of other implications for e.g. spike width.

**Comment by russelljjarvis** [comment]
![debug](https://user-images.githubusercontent.com/7786645/52926594-a9e04600-32f3-11e9-995f-28b1c6f4e393.png)

**Comment by russelljjarvis** [comment]
That's one example.

**Comment by russelljjarvis** [comment]
So maybe I just need to tweak:
```
    'v_spike':  -40.0,     # Spike detection threshold in mV.
    'v_thresh': -50.4,     # Spike initiation threshold in mV
```

**Comment by rgerkin** [comment]
I think if you just set `v_spike` to something like +30 mV it will work.  The spikes might look weird, but no weirder than they do for an Izhikevich neuron.

**Comment by russelljjarvis** [comment]
This probably fixed problem.

**Comment by russelljjarvis** [comment]
![image](https://user-images.githubusercontent.com/7786645/52971571-2cf5b080-3375-11e9-9fe1-685aa541afc6.png)

**Comment by russelljjarvis** [comment]
![image](https://user-images.githubusercontent.com/7786645/52972050-cf626380-3376-11e9-9a22-ab9cc877066b.png)
