### ISSUE TITLE
improved documentation:

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/neuronunit#18]
@rgerkin

https://github.com/russelljjarvis/neuronunit/blob/russell_dev/docs/chapter5.ipynb

I recently added into the beginning of the nb instructions on how to launch (the exact docker env used, and the directory the NB server is launched mounted within/ launched from). I think it could be merged at least with: 

`-b russell_dev scidash/neuronunit`

I will move more junk into scratch in order to make a pull request less irritating from your end. I have also already cleaned up somewhat.

**Comment by rgerkin** [comment]
Chapter 5 is already merged into master.
