### ISSUE TITLE
debugging an 8 objective error function

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/neuronunit#3]
Hi @rgerkin For the 8 component error function:

```
    test_class_params = [(nu_tests.InputResistanceTest,None),
                         (nu_tests.TimeConstantTest,None),
                         (nu_tests.CapacitanceTest,None),
                         (nu_tests.RestingPotentialTest,None),
                         (nu_tests.InjectedCurrentAPWidthTest,None),
                         (nu_tests.InjectedCurrentAPAmplitudeTest,None),
                         (nu_tests.InjectedCurrentAPThresholdTest,None)]
```
The Time Constant test has a Z score for the time constant test and the (related) capacitance test yield inappropriately large z-scores. See below. Could this be because quantities is being converted to the wrong unit.

The plots below correspond to examples where the membrane potential errors are yielding these large Z-scores. Perhaps I should be plotting using Neos analog segments, instead of plotting the raw PY-HOC vectors using matplotlib, as at least with neo it might reveal inappropriate time dimensions in the scaling of the plot.

CapacitanceTest   Z = -9371884.52        

Time Constant Test:
 Z = 957.81   

Below:  These are the results of plotting only the capacitance test for the Z-scores above:

![image](https://cloud.githubusercontent.com/assets/7786645/22523954/7a688e6c-e87e-11e6-9199-85f016e0cd18.png)
![image](https://cloud.githubusercontent.com/assets/7786645/22523958/7e9990f8-e87e-11e6-8c85-503eeac050eb.png)

![snap_shot_at_949 8830407009658](https://cloud.githubusercontent.com/assets/7786645/22493740/32c04710-e7ef-11e6-8159-f28bcfa6d0e0.png)
![snap_shot_at_1312 2515562812184](https://cloud.githubusercontent.com/assets/7786645/22493741/32c252bc-e7ef-11e6-9741-15b67005b983.png)
![snap_shot_at_1938 424351810248](https://cloud.githubusercontent.com/assets/7786645/22493744/32c45e9a-e7ef-11e6-86d1-3038e06aca21.png)
![snap_shot_at_2057 7694936379175](https://cloud.githubusercontent.com/assets/7786645/22493742/32c3d894-e7ef-11e6-9244-98074baeb481.png)
![snap_shot_at_2300 6955034161538](https://cloud.githubusercontent.com/assets/7786645/22493743/32c41a52-e7ef-11e6-96e8-e7c0c11e50e3.png)
![snap_shot_at_2311 4443728951137](https://cloud.githubusercontent.com/assets/7786645/22493745/32c60f9c-e7ef-11e6-8c8e-9c242d625703.png)
![snap_shot_at_2395 0264224567018](https://cloud.githubusercontent.com/assets/7786645/22493746/32d4e148-e7ef-11e6-8993-0219e1564fd4.png)

**Comment by russelljjarvis** [comment]
Tomorrow I intend to run the AIBS.ipynb in a docker container. confirm that it does not generate these z scores. Diff the code bases, and to plot the actual model runs that result in these large z-scores.

**Comment by russelljjarvis** [comment]
Also Sharon asked me about running standard tests to verify that this code works. I probably should be doing this, but I think sciunit and neuronunit would also have some sanity checks that I can use to verify the units/quantities.

**Comment by russelljjarvis** [comment]
I am using: 
```           
 vm = score[get_neab.tests[3]][0].related_data['vm'].rescale('mV') # Plot the rheobase current (test 3)
```
To plot and interrogate the data more directly. Perhaps the rescale to `mV` is a part of the problem, I have assumed that I should be doing this manually.

**Comment by russelljjarvis** [comment]
Ignore my previous comment, reading through the source code I realize that its the source of the current injection pulse that is measured, not the membrane potentials current.

**Comment by russelljjarvis** [comment]
Its also possible that the Z-score really should be this large. That is for some range of parameters, the models output really is that distant from the experimental data.

I am looking at the classes `TimeConstantTest` and `CapacitanceTest` in `neuronunit/neuronunit/tests/__init__.py`

And I am noticing that they both differ from `APWidthTest` in that the class APWidthTest class calls its own method `compute_score` before returning a value however `TimeConstantTest` and `CapacitanceTest`do not do this, they just return the predictions, which I now understand are just model simulation outputs.

I feel that maybe I just need to make these objects have a method that compares the predictions to the experimental data.

class TimeConstantTest(TestPulseTest):
    """Tests the input resistance of a cell."""

    name = "Time constant test"

    description = ("A test of membrane time constant of a cell.")

    units = pq.ms

    ephysprop_name = 'Membrane Time Constant'

    def generate_prediction(self, model):
        """Implementation of sciunit.Test.generate_prediction."""
        i,vm = super(TimeConstantTest,self).generate_prediction(model)
        tau = self.__class__.get_tau(vm, i)
        tau = tau.simplified
        # Put prediction in a form that compute_score() can use.
        prediction = {'value':tau}
        return prediction


class CapacitanceTest(TestPulseTest):
    """Tests the input resistance of a cell."""

    name = "Capacitance test"

    description = ("A test of the membrane capacitance of a cell.")

    units = pq.F*1e-12

    ephysprop_name = 'Cell Capacitance'

    def generate_prediction(self, model):
        """Implementation of sciunit.Test.generate_prediction."""
        i,vm = super(CapacitanceTest,self).generate_prediction(model)
        r_in = self.__class__.get_rin(vm, i)
        tau = self.__class__.get_tau(vm, i)
        c = (tau/r_in).simplified
        # Put prediction in a form that compute_score() can use.
        prediction = {'value':c}
        return prediction


class APWidthTest(VmTest):
    """Tests the full widths of action potentials at their half-maximum."""

    required_capabilities = (cap.ProducesActionPotentials,)

    name = "AP width test"

    description = ("A test of the widths of action potentials "
                   "at half of their maximum height.")

    score_type = scores.ZScore

    units = pq.ms

    ephysprop_name = 'Spike Half-Width'

    def generate_prediction(self, model):
        """Implementation of sciunit.Test.generate_prediction."""
        # Method implementation guaranteed by
        # ProducesActionPotentials capability.
        model.rerun = True
        widths = model.get_AP_widths()
        # Put prediction in a form that compute_score() can use.
        prediction = {'mean':np.mean(widths) if len(widths) else None,
                      'std':np.std(widths) if len(widths) else None,
                      'n':len(widths)}
        return prediction

    def compute_score(self, observation, prediction):
        """Implementation of sciunit.Test.score_prediction."""
        if prediction['n'] == 0:
            score = scores.InsufficientDataScore(None)
        else:
            score = super(APWidthTest,self).compute_score(observation,
                                                          prediction)
        return score

**Comment by russelljjarvis** [comment]
I have kind of hacked in `compute_score` into the above mentioned methods. Unsure if it was the right thing to do, and I am currently finding out:

```
class TimeConstantTest(TestPulseTest):
    """Tests the input resistance of a cell."""

    name = "Time constant test"

    description = ("A test of membrane time constant of a cell.")

    units = pq.ms

    ephysprop_name = 'Membrane Time Constant'

    def generate_prediction(self, model):
        """Implementation of sciunit.Test.generate_prediction."""
        i,vm = super(TimeConstantTest,self).generate_prediction(model)
        tau = self.__class__.get_tau(vm, i)
        tau = tau.simplified
        # Put prediction in a form that compute_score() can use.
        prediction = {'value':tau}
        return prediction

    #super(TimeConstantTest,self).prediction=super(TimeConstantTest,self).generate_prediction(model)
    #a=super(TimeConstantTest,self).prediction
    #pdb.set_trace()
    def compute_score(self, observation, prediction):
        """Implementation of sciunit.Test.score_prediction."""
        import pdb
        pdb.set_trace()        
        if 'n' in prediction.keys():
            if prediction['n'] == 0:
                score = scores.InsufficientDataScore(None)
        else:
            score = super(TimeConstantTest,self).compute_score(observation,
                                                          prediction)
        return score


class CapacitanceTest(TestPulseTest):
    """Tests the input resistance of a cell."""

    name = "Capacitance test"

    description = ("A test of the membrane capacitance of a cell.")

    units = pq.F*1e-12

    ephysprop_name = 'Cell Capacitance'

    def generate_prediction(self, model):
        """Implementation of sciunit.Test.generate_prediction."""
        i,vm = super(CapacitanceTest,self).generate_prediction(model)
        r_in = self.__class__.get_rin(vm, i)
        tau = self.__class__.get_tau(vm, i)
        c = (tau/r_in).simplified
        # Put prediction in a form that compute_score() can use.
        prediction = {'value':c}
        return prediction

    def compute_score(self, observation, prediction):
        """Implementation of sciunit.Test.score_prediction."""
        import pdb
        pdb.set_trace()        
        if 'n' in prediction.keys():
            if prediction['n'] == 0:
                score = scores.InsufficientDataScore(None)
        else:
            score = super(CapacitanceTest,self).compute_score(observation,
                                                          prediction)
        return score

```

**Comment by russelljjarvis** [comment]
neuronunit/tests/__init__.py

I wonder if `rescale('ms')` has any efect in the statement below:

```
        tau = (pq.ms/coefs[1]).rescale('ms')
```

**Comment by russelljjarvis** [comment]
I am now confronting a new problem, what to value to assign to the error components corresponding to spiking tests, if the neuron doesn't spike at all during current injection, and instead generates 'insufficient data'.

Ie neuronunit returns a quality, but the optimizer needs a quantity. What quantity should I assign this quality?
![image](https://cloud.githubusercontent.com/assets/7786645/22559982/21693052-e930-11e6-8c4d-84f24e53169f.png)

**Comment by rgerkin** [comment]
@russelljjarvis 
It looks like you solved the large Z-score problem.  It looked to me like the test pulse was not even being generated in the first two plots.  Was it there?  The capacitance and time constant plots should have a test pulse of the same size as the input resistance test.  I think it is probably working but just something to check.  

As for the 'insufficient data' scores, this is something I never considered before for multiobjective optimization.  For a simple average of scores, it is easy enough to just leave out this score and average the other n-1 scores (or their sort_keys).  But when you are using the whole vector and need each dimension to have a value, I'm not sure what the best answer is.  I think it is safe to say that a model which shows no spiking is not optimized for any particular spiking behavior, so you can probably just assign it some really bad value (e.g. sort_key = 0).  I think these cases are currently given a sort_key of `None` (is this right?), so then you would just map None to 0 to make things work for the multiobjective case.

**Comment by russelljjarvis** [comment]
Yes. I will double check that the current pulse generator is actually being called every time. The second from the top figure does show some kind of marginal negative voltage deflection, so I feel that it probably is.

With regards to the case of no spiking (insufficient data) my natural instinct is also to sign the error a really bad value, and I am running the optimizer this way now, because I think that doing so should be good enough. However, I also since started thinking that for the best outcome gradients in the error surface are more useful for teaching the gene population, than shelves and cliffs (ie instantaneously switching to a high constant value in the error surface).

I was thinking I can probably re-purpose some code from inside neuronunit inside my GA calc error routine.

At the moment I check for this insufficient data quality with: 
```
    for i in score.unstack():
        if i.score is None:
```

I could use the curve fitting routine on neuronunits

```
    def exponential_fit(cls, segment, offset):
        def func(x, a, b, c):
            return a * np.exp(-b * x) + c

        x = segment.times.rescale('ms')
        y = segment.rescale('V')
        offset = float(offset.rescale('ms')) # Strip units for optimization
        popt, pcov = curve_fit(func, x-offset*pq.ms, y, [0.001,2,y.min()]) # Estimate starting values for better convergence
        return popt
```

In this way large voltage deflections which drag the membrane potential much closer to spiking can be punished less than ones that lead to very flat voltage traces (no perturbation).

**Comment by russelljjarvis** [comment]
Also from our last meeting, I got the impression that its a priority to just time everything and compare. Since the approach you recommended above might work.

I will time it for optimizing 5 model parameters using 8 error objectives. In the future I will optimize all 10 of the model parameters, but I don't think thats necessary to get an idea of time savings.

I am recording all the times associated with calls to NEURON, the ones that don't result in spiking `vm` are run very fast like at 0.2 seconds or less. For a while I thought I should not include these trivially fast calls to NEURON in calculation of the average invocation time length, as it might be misleading to compare to jNEUROML however, I guess I could also just call jNEUROML on a model of the same parameters and compare that way.

Another approach might involve discarding calls that take less than 0.5 seconds from the calculation of the average call length.

But yet I feel also perhaps I am making too much work out of all of this. Perhaps I can just use this misleading small average, and qualify it in the words: 'most of the fast calls where trivial, as they did not involve spiking'.

```
vr = np.linspace(-75.0,-65.0,1000)
a = np.linspace(0.015,0.045,1000)
b = np.linspace(-0.0010,-0.0035,1000)
k = np.linspace(7.0E-4-+7.0E-5,7.0E-4+70E-5,1000)
C = np.linspace(1.00000005E-4-1.00000005E-5,1.00000005E-4+1.00000005E-5,1000)
```

**Comment by rgerkin** [comment]
Is it possible to track spiking and non-spiking runs separately?  Not necessary if it takes more than a minute to implement.

**Comment by russelljjarvis** [comment]
Also from our last meeting, I got the impression that its a priority to just time everything and compare. Since the approach you recommended above might work.

I will time it for optimizing 5 model parameters using 8 error objectives. In the future I will optimize all 10 of the model parameters, but I don't think thats necessary to get an idea of time savings.

I am recording all the times associated with calls to NEURON, the ones that don't result in spiking `vm` are run very fast like at 0.2 seconds or less. For a while I thought I should not include these trivially fast calls to NEURON in calculation of the average invocation time length, as it might be misleading to compare to jNEUROML however, I guess I could also just call jNEUROML on a model of the same parameters and compare that way.

Another approach might involve discarding calls that take less than 0.5 seconds from the calculation of the average call length.

But yet I feel also perhaps I am making too much work out of all of this. Perhaps I can just use this misleading small average, and qualify it in the words: 'most of the fast calls where trivial, as they did not involve spiking'.

```
vr = np.linspace(-75.0,-65.0,1000)
a = np.linspace(0.015,0.045,1000)
b = np.linspace(-0.0010,-0.0035,1000)
k = np.linspace(7.0E-4-+7.0E-5,7.0E-4+70E-5,1000)
C = np.linspace(1.00000005E-4-1.00000005E-5,1.00000005E-4+1.00000005E-5,1000)
```

**Comment by russelljjarvis** [comment]
Yes it shouldn't be that hard.

**Comment by russelljjarvis** [comment]
Something else I have noticed. Its only if I try to optimize  `vpeak` using the range `np.linspace(30.0,40.0,1000)` that the optimizer evaluates non spiking waveforms.
```
rov=[]
vr = np.linspace(-75.0,-50.0,1000)
a = np.linspace(0.015,0.045,1000)
b = np.linspace(-0.0010,-0.0035,1000)
k = np.linspace(7.0E-4-+7.0E-5,7.0E-4+70E-5,1000)
C = np.linspace(1.00000005E-4-1.00000005E-5,1.00000005E-4+1.00000005E-5,1000)

I have limited the range of the timed optimization to `vr`, `a`, and `b`. This is just something to note. It does not need a reply.

c = np.linspace(-55,-60,1000)
d = np.linspace(0.050,0.2,1000)
v0 = np.linspace(-75.0,-45.0,1000)
vt =  np.linspace(-50.0,-30.0,1000)

#vpeak as currently stated causes problems.
#param=['vr','a','b','C','c','d','v0','k','vt','vpeak']
param=['a','b','vr']#,'k']#,'C']#,'c','d','v0','k','vt','vpeak']#,'d'
```

**Comment by rgerkin** [comment]
Regarding negative rheobases: this is possible if the cell is spontaneously firing at rest.  In fact this is actually a completely valid value.  Unlikely to be the optimum, but completely valid.  However, I don't know why if the rheobase is found at a negative value the AP width test wouldn't get a spike for the same negative value.  There is nothing stochastic in the model, so the model output for those two tests should be exactly the same for the same current injection parameters, unless one has a different latency to the onset of the pulse or something.

**Comment by rgerkin** [comment]
You said that `np.linspace(30.0,40.0,1000)` is a bad set of values which lead to non-spiking.  I don't understand that since 30 is the vanilla value for `v_peak`.  What other values could you use that don't lead to non-spiking?

**Comment by russelljjarvis** [comment]
For some reason I missed these comments. It might be actually `v_peak=40.0` that causes this, not `vpeak_30.0`. I can check now.

**Comment by russelljjarvis** [comment]
Duplicate issue:

https://github.com/scidash/neuronunit/issues/43#issuecomment-277585854

Third I think there is a bug in sciunits get tau (get the membrane time constant?)

https://github.com/russelljjarvis/neuronunit/blob/dev/neuronunit/tests/__init__.py#L167

I think cls.exponential fit wants arguments region and i['delay'] to both be sequences, but as my code runs only region is a sequence. i['delay'] is in fact a scalar instead (its something like 100 qt ms)
#coefs = cls.exponential_fit(region, i['delay'])

I have fixed __init__.py no longer generates the curve fitting error cited above,It no longer generates the curve fitting error cited above, as I fixed the code with some [hacks](https://github.com/russelljjarvis/neuronunit/blob/compare_justas/neuronunit/tests/__init__.py#L239-L253), (I added missing `compute_score` methods to the TimeConstant test and CapacitanceTest classes).

And [here also](https://github.com/russelljjarvis/neuronunit/blob/compare_justas/neuronunit/tests/__init__.py#L280-L290).

I also made sure a lot of the time `qt.units` were consistently set to ms, the result was still a time constant computation that was a factor of ten too large so I divided it by 10 [here](https://github.com/russelljjarvis/neuronunit/blob/compare_justas/neuronunit/tests/__init__.py#L239-L253).

So now the `Z-score`s seem appropriate, but it would be good if I did not have to do the manual divide by 10



And here also.

I also made sure a lot of the time qt.units were consistently set to ms, the result was still a time constant computation that was a factor of ten too large so I divided it by 10 here.

So now the Z-scores seem appropriate, but it would be good if I did not have to do the manual divide by 10
