### ISSUE TITLE
Copy scidash@dev's capabilities/__init__.py file over yours

### ISSUE THREAD

**Issue by rgerkin** [russelljjarvis/neuronunit#30]
You implemented the capabilities inside the capabilities files as a quick solution, but in general the capabilities should be left unimplemented in that location and implemented instead in the model.  Now that the backend has a simpler implementation, your implementation of these capabilities that is already in the model or the backend should just work now and not give a "NotImplementedError".  So just copy the scidash version over yours to re-unimplement the capabilities in capabilities/__init__.py.

**Comment by russelljjarvis** [comment]
Done.
