### ISSUE TITLE
Get rid of intermediate prediction capture

### ISSUE THREAD

**Issue by rgerkin** [russelljjarvis/neuronunit#34]
Remove things like this:  

```
def __init__(self):
        super(InputResistanceTest).__init__()
        self.prediction = None
```
since you can just access the prediction from the score that the test returns.

**Comment by russelljjarvis** [comment]
Done. See [file](https://github.com/russelljjarvis/neuronunit/blob/dev/neuronunit/tests/__init__.py
), which is now empty of intermediate prediction captures.
