### ISSUE TITLE
Copy serial rheobase test from scidash@dev to be next to your parallel rheobase test

### ISSUE THREAD

**Issue by rgerkin** [russelljjarvis/neuronunit#35]
Give them each different names and/or put them in different files.

**Comment by russelljjarvis** [comment]
This one is done too.

Serial Rheobase class has signature `RheobaseTest` parallel has signature: `RheobaseTestP`

Probably when I test that serial == parallel in unit_testing I will have to edit `get_neab` such that when it constructs the whole suite, both versions of RT are constructed.
