### ISSUE TITLE
Trying to satisfy or silence warnings in parallel unit testing:

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/neuronunit#39]
```
/opt/conda/lib/python3.5/site-packages/ipyparallel/util.py:511: DeprecationWarning: Interpreting naïve datetime as local 2017-10-24 18:58:40.289870. Please add timezone info to timestamps.
  new_obj[k] = extract_dates(v)
```

**Comment by rgerkin** [comment]
Do you know where the timestamp object is in the code?

**Comment by russelljjarvis** [comment]
Not exactly. There are a lot of references to timestampt object in ipyparallel/util.py I can't tell if any of these are the first instance of the timestamp object however. For some reason these warnings are only visible when I am using running a script with the unittesting module.

I assume it is somewhere in ipyparallel. I should try to run run ```grep -r "timestamp" *.py``` inside /ipyparallel

**Comment by rgerkin** [comment]
You can use warnings.filterwarnings if you want and just turn it off.

**Comment by russelljjarvis** [comment]
AOK.
