### ISSUE TITLE
Intergration of  neuronunit/neuron/models.py with backends.py

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/neuronunit#4]
[Test code](https://github.com/JustasB/MitralSuite/blob/master/README.md#simple-model-example) for after the merge:

Hi @JustasB, 

I have been thinking more about this issue. I was wondering if you could remind me again what the original use case was for `[neuron/models.py](https://github.com/russelljjarvis/neuronunit/blob/master/neuronunit/neuron/models.py) `? was this for using `neuronunit` on the Mitrial cells in the olfactory bulb model? I need to know a bit more about this use case, such that the file we produce as an outcome of the merge can still perform the function you used it for, as well as the function I am using it for.

The file that I am going to merge it into is located [here](https://github.com/russelljjarvis/neuronunit/blob/compare_justas/neuronunit/models/backends.py)

I think I have resolved some issues in the discussion below, however one remaining issue as I see it is how to build the HOC space model using JNeuroML if one doesn't exist already. Thinking out loud: 'perhaps I can factor out the checking for the existence of a HOC space model and the conditionally building of it into a different a different method and file that is called outside of and before the contents of this file are executed in my use case?'

Your method for `inject_square_current` is shorter and easier to read than mine. However the approach of checking if the `iclamp` object is an attribute of the `h` object will not or cannot work yet, because the way jNeuroML works it does not translate variable names from the XML file into generic NEURON variables like `iclamp`, 
```
if not hasattr(self, 'iclamp'):
     self.iclamp = self.h.IClamp(self.getSegment())
```
To achieve the same thing I first have to search the original xml tree of the neuroml file to find out what the variable name for the pulseGenerator object was, and then I store its name in a python dictionary for later use.
```     
        more_attributes=pynml.read_lems_file(self.orig_lems_file_path)
        for i in more_attributes.components:
        #This code strips out simulation parameters from the xml tree also such as duration.
        #Strip out values from something a bit like an xml tree.
            if str('pulseGenerator') in i.type:
                self.current_src_name=i.id
            if str('Cell') in i.type:
                self.cell_name=i.id
        more_attributes=None#force garbage collection of more_attributes, its not needed anymore.
```
Later in `inject_square_current` I use the original current sources name when I execute a `hoc` string. However just thinking out load now, probably I can discard the current sources original name and associate its value with an iclamp attribute of the `self` instance object, and that way we can keep your inject_square_current method without modification. 

```       self.h('explicitInput_'+str(self.current_src_name)+str(self.cell_name)+'_pop0.'+str('amplitude')+'='+str(amps))  self.h('explicitInput_'+str(self.current_src_name)+str(self.cell_name)+'_pop0.'+str('duration')+'='+str(c['duration']))
self.h('explicitInput_'+str(self.current_src_name)+str(self.cell_name)+'_pop0.'+str('delay')+'='+str(c['delay']))

```

```
def inject_square_current(self,current):
        """Injects somatic current into the model.
        Parameters
        ----------
        current : a dictionary like:
                        {'amplitude':-10.0*pq.pA,
                         'delay':100*pq.ms,
                         'duration':500*pq.ms}}
                  where 'pq' is the quantities package
        This describes the current to be injected.
        """

        # Set the units to those expected by NEURON IClamp
        amp = current['amplitude']
        amp.units = nA

        dur = current['duration']
        dur.units = ms

        delay = current['delay']
        delay.units = ms

        if not hasattr(self, 'iclamp'):
            self.iclamp = self.h.IClamp(self.getSegment())

        self.iclamp.delay = float(delay)
        self.iclamp.dur = float(dur)
        self.iclamp.amp = float(amp)

        self.h.run()
```

I think we should keep all of the following methods, unless you say otherwise, although I am not using them they might be important to the functionality of your use case:

```
    def setStopTime(self, stopTime = 1000*ms):
        """Sets the simulation duration"""
        """stopTimeMs: duration in milliseconds"""

        tstop = stopTime
        tstop.units = ms

        self.h.tstop = float(tstop)
    
    def setTimeStep(self, integrationTimeStep = 1/128.0 * ms):
        """Sets the simulation itegration fixed time step"""
        """integrationTimeStepMs: time step in milliseconds. Powers of two preferred. Defaults to 1/128.0"""

        dt = integrationTimeStep
        dt.units = ms

        self.h.dt = self.fixedTimeStep = float(dt)

    def setTolerance(self, tolerance = 0.001):
        """Sets the variable time step integration method absolute tolerance """
        """tolerance: absolute tolerance value"""
        
        self.h.cvode.atol(tolerance)
    
    def setIntegrationMethod(self, method = "fixed"):
        """Sets the simulation itegration method"""
        """method: either "fixed" or "variable". Defaults to fixed. cvode is used when "variable" """
        
        self.h.cvode.active(1 if method == "variable" else 0)


    def get_variable_step_analog_signal(self):
        """ Converts variable dt array values to fixed dt array by using linear interpolation"""

        # Fixed dt potential
        fPots = []
        fDt = self.fixedTimeStep

        # Variable dt potential
        vPots = self.vVector.to_python()

        # Variable dt times
        vTimes = self.tVector.to_python()

        duration = vTimes[len(vTimes)-1]

        # Fixed and Variable dt times
        fTime = vTime = vTimes[0]

        # Index of variable dt time array
        vIndex = 0

        # Advance the fixed dt position
        while fTime <= duration:

            # If v and f times are exact, no interpolation needed
            if fTime == vTime:
                fPots.append(vPots[vIndex])

            # Interpolate between the two nearest vdt times
            else:

                # Increment vdt time until it surpases the fdt time
                while fTime > vTime and vIndex < len(vTimes):
                    vIndex += 1
                    vTime = vTimes[vIndex]

                # Once surpassed, use the new vdt time and t-1 for interpolation
                vIndexMinus1 = max(0, vIndex-1)
                vTimeMinus1 = vTimes[vIndexMinus1]

                fPot = self.linearInterpolate(vTimeMinus1, vTime, \
                                          vPots[vIndexMinus1], vPots[vIndex], \
                                          fTime)

                fPots.append(fPot)

            # Go to the next fdt time step
            fTime += fDt

        return fPots

    def linearInterpolate(self, tStart, tEnd, vStart, vEnd, tTarget):
        tRange = float(tEnd - tStart)
        tFractionAlong = (tTarget - tStart)/tRange

        vRange = vEnd - vStart

        vTarget = vRange*tFractionAlong + vStart

return vTarget
```
I was thinking of factoring these methods out of the file merger as these methods are now inherited from a different class `ReducedModel`
```
def get_spike_train(self):
        """Gets computed spike times from the model.
        Arguments: None.
        Returns: a neo.core.SpikeTrain object.
        """

        return spike_functions.get_spike_train(self.get_membrane_potential())
    
    def get_APs(self):
        """Gets action potential waveform chunks from the model.
            
        Returns
        -------
        Must return a neo.core.AnalogSignalArray.
        Each neo.core.AnalogSignal in the array should be a spike waveform.
        """
        
        return spike_functions.get_spike_waveforms(self.get_membrane_potential())

```

**Comment by russelljjarvis** [comment]
One other thing though. Do you have some code I can run in order to test if the merged version of the files still passes your use case as well as mine?

When I first wrote `Backends.py `I think I had your `get_spike_train` and `get_membrane_potential` methods in it, which work well by the way.

But then Rick encouraged me to inherit those same methods from Reduced Model. As long as the hoc results are recorded in vectors and then put in a dictionary container
the inherited ReducedModel methods get_APs can act on them in an identical way.

See here for an example of how NEURON simulation results are stored in a dictionary:
https://github.com/russelljjarvis/neuronunit/blob/compare_justas/neuronunit/models/backends.py#L215-L216
Later they are acted on by the inherited versions of 
`def get_spike_train(self):`
`def get_APs(self):`

However your method for `get_membrane_potential(self):` is actually significantly different from the inherited version so I will use that for sure.

Also relating to what you have said above, that being able to optionally pass in as an argument specific section, and segments into a multicompartmental object is also important.

I think the means that if these arguments are present, I conditionally record in the same way that you have below.
```
def __init__(self, \
hVar, \
section, \
loc = 0.5, \
name=None):

.
.
.

super(SingleCellModel,self).__init__(name=name, hVar=hVar)
self.setSegment(section, loc)
self.vVector.record(self.getSegment()._ref_v)
self.tVector.record(self.h._ref_t)
```
```
get_membrane_potential(self, rerun=None, **run_params):
if rerun is None:
rerun = self.rerun
self.run(rerun=rerun, **run_params)
for rkey in self.results.keys():
if 'v' in rkey or 'vm' in rkey:
v = np.array(self.results[rkey])
t = np.array(self.results['t'])
dt = (t[1]-t[0])*pq.ms # Time per sample in milliseconds.
vm = AnalogSignal(v,units=pq.V,sampling_rate=1.0/dt)
return vm
```

```
def get_APs(self, rerun=False, **run_params):
vm = self.get_membrane_potential(rerun=rerun, **run_params)
waveforms = sf.get_spike_waveforms(vm)
return waveforms
def get_spike_train(self, rerun=False, **run_params):
vm = self.get_membrane_potential(rerun=rerun, **run_params)
spike_train = sf.get_spike_train(vm)
return spike_train
```

```
def get_membrane_potential(self, rerun=None, **run_params):
if rerun is None:
rerun = self.rerun
self.run(rerun=rerun, **run_params)
for rkey in self.results.keys():
if 'v' in rkey or 'vm' in rkey:
v = np.array(self.results[rkey])
t = np.array(self.results['t'])
dt = (t[1]-t[0])*pq.ms # Time per sample in milliseconds.
vm = AnalogSignal(v,units=pq.V,sampling_rate=1.0/dt)
return vm
```

```
self.results={}
self.results['vm'] = [ float(x/1000.0) for x in self.neuron.h.v_v_of0.to_python() ] # Convert to Python list for speed, variable has dim: voltage
self.results['t'] = [ float(x) for x in self.neuron.h.v_time.to_python() ] 
```

**Comment by russelljjarvis** [comment]
This has been shifted to top priority.

**Comment by rgerkin** [comment]
@russelljjarvis @JustasB Does this code work for Justas (the code in `neuronunit:master` with `scidash:master` as of right now) for his NEURON work?  Justas, maybe you could write a unit test that would test your model and we could use that to just check it periodically instead of making you do it each time.

**Comment by rgerkin** [comment]
@russelljjarvis Can you add @JustasB to the list of collaborators on your fork so I can assign him to issues like this?

**Comment by russelljjarvis** [comment]
Yes.
