### ISSUE TITLE
Development Strategy 4 Different Directions.

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/neuronunit#7]
At the moment there are 5 independent paths that Neuronunit Development can take. Each path has many man hours involved. 

I have chosen 2. 4 and 5 for the short term. But this does not exclude doing 1 and 3 in the medium term (3 and 5 will not improve speed but they will improve code maintainability and quality).

# 1 
There is integrating Justas' neuron/models.py file with my existing Backends.py file. This will happen at some point.

# 2 
There is parallelizing the Rheobase search. A first pass at this is translating the existing algorithm to use pythons default serial `map` function, doing so will facilitate using `futures.map` in the future. Doing so might result in significant time savings on NSG and travis.

# 3 
Reconciling my GA approach with the BluePyOpt and as a corollary using `ipyparallel` as an alternative to `scoop futures map`. I have been playing with the BluePyOpt code base  together with ipyparallel for a while now, and there is no guarantee that this will work, however it is a theoretically attractive. Since the end result of such an integration, would mean well supported abstracted, simplified and easier to maintain code, it would also mean that the end result could be an jupyter notebook very similar to AIBS.ipynb that is generated in a fraction of time.

# 4 
Emailing the NSG to get our dockerbuild for the NSG supported. 

# 5
Making it such that the non spiking regions of the parameter space can be explored. This is equivalent to handling an exception that is caused when an error component is assigned the `N/A` or `not enough data scores`

Since the first 3 out of the 4 of these directions have significant man hours associated them, its difficult for me to figure out which is a larger priority for you. Today I have been working on 2as I think it would make the exhaustive search faster also, and I think I will also work on 5 since the GA can be used more broadly if its behavior is more robust..

**Comment by russelljjarvis** [comment]
I am currently in a place where I feel that there are multiple development paths again, and I am having trouble selecting the highest impact path.

Currently I could:
#1 Create a dockerbuild that would enable you to run a big multi-objective, exhaustive_search run on the maths cluster account that Renate has given you access to. I feel that building a docker container like this is of limited utility, since it would not be very high cost to execute an existing docker build, enter it manually, and change `nparam`, `npoints`, `NGEN`, `MU`.

#2 Work on developing better graphs for the existing ipython-notebook, although developing the code outside of notebook. This is partially done and it would be good for the release if it has not already happened.

# 3 Although the exhaustive test/ NSGA algorithm agreement is now good with 3 parameters, its unknown if it remains good with 4 or more. A previous attempt with only 2 different parameters was not good decreasing Cross over Probability CXP, and changing the parameters seemed to help, unfortunately I altered both simultaneously, so I need to find out which change made the impact.

# 4 If NSGA/exhaustive minima agreement remains good, under bigger parameter sets, return to cases where prediction/observation agreement was bad, but the sciunit score (which informs the search error) was good. Plot the corresponding `$v_{m}$'s` as visualizing the membrane potential may reveal the source of the confusion.

**Comment by rgerkin** [comment]
At some point we need to deliver on the aims of the Reduced Models grant, which will require being able to complete the optimization with all of the parameters.  So I would work on debugging any issues that arise as you add parameters to the optimization (I don't care too much about npoints, ngen, etc. except as they impact the ability of the code to converge on something near a global optimum).  If adding visualization helps you do that, then that is something you could work on as well.  Don't worry about 1 and 4.  Don't worry about prediction/observation agreement either unless you have cases where it cannot be explained by high SEM in the observation, in which case it might be a bug.

**Comment by russelljjarvis** [comment]
AOK. This sounds good. I am running some full 10 parameter sparsely sampled optimization routines currently to fulfil this end. 

In this context I think high SEM stands for Standard Mean Error.

**Comment by rgerkin** [comment]
SEM standard for standard error of the mean, i.e. if an observation has high SEM, then we are actually quite uncertain about the true mean.  When SEM is high, is takes a larger deviation of prediction from observation to produce a Z-score far from zero (because Z-score is that deviation divided by SEM, basically).  In those cases, the optimizer may allow the prediction to get pretty far away from the observation, because the Z-score isn't getting that far away, i.e. the large SEM corresponds to a small "penalty".
